import { SchoolProfile, Siswa, Guru, ArchiveItem, UserAccount } from '../types';

export interface SeedSchoolInfo {
  npsn: string;
  namaSekolah: string;
  tingkat: 'SD' | 'SMP';
  wilayah: string;
  profile: SchoolProfile;
  accounts: UserAccount[];
  siswa: Siswa[];
  guru: Guru[];
  archives: ArchiveItem[];
}

export const SEED_SCHOOLS: SeedSchoolInfo[] = [
  {
    npsn: '20202020',
    namaSekolah: 'SD NEGERI 2 NYOMPLONG',
    tingkat: 'SD',
    wilayah: 'Kota Sukabumi, Jawa Barat',
    profile: {
      pemerintah: 'PEMERINTAH KOTA SUKABUMI',
      dinas: 'DINAS PENDIDIKAN DAN KEBUDAYAAN',
      cabangDinas: '',
      namaSekolah: 'SD NEGERI 2 NYOMPLONG',
      npsn: '20202020',
      akreditasi: 'Akreditasi A (Unggul)',
      alamat: 'Jl. Nyomplong No. 45, RT.02/RW.04',
      kelurahan: 'Nyomplong',
      kecamatan: 'Warudoyong',
      kota: 'Kota Sukabumi',
      provinsi: 'Jawa Barat',
      kodePos: '43131',
      telepon: '(0266) 223344',
      email: 'sdn2nyomplong@sukabumikota.sch.id',
      website: 'www.sdn2nyomplong.sch.id',
      namaKepsek: 'Hj. Siti Rohmah, M.Pd.',
      nipKepsek: '197405121998032004',
      pangkatKepsek: 'Pembina Tk. I, IV/b',
      jabatanKepsek: 'Kepala Sekolah',
      showStempel: true,
      showTTD: true,
      showQRCode: false,
      operatorAvatarUrl: 'https://picsum.photos/seed/riki-mulyadi/150/150',
      operatorBadge: 'Operator Sekolah',
      operatorName: 'Riki Mulyadi',
      operatorSubtitle: 'Admin Tata Usaha',
      operatorChecklistTitle: 'ADMINISTRASI SEKOLAH',
      operatorChecklistItems: ['Data Siswa', 'Surat & Arsip Digital'],
      logoLeftUrl: 'https://illustrations.popsy.co/indigo/academic-cap.svg',
      logoRightUrl: 'https://illustrations.popsy.co/indigo/academic-cap.svg',
    },
    accounts: [
      {
        username: 'admin.nyomplong',
        namaLengkap: 'Riki Mulyadi',
        role: 'Admin TU',
        password: '123',
        avatarUrl: 'https://picsum.photos/seed/riki-mulyadi/150/150',
        createdAt: '2026-08-01',
        jabatan: 'Kepala Tata Usaha',
        npsn: '20202020',
        namaSekolah: 'SD NEGERI 2 NYOMPLONG',
        kabupaten: 'Kota Sukabumi',
        kecamatan: 'Warudoyong',
        desa: 'Nyomplong',
        alamat: 'Jl. Nyomplong No. 45',
        provinsi: 'Jawa Barat',
      },
      {
        username: 'kepsek.nyomplong',
        namaLengkap: 'Hj. Siti Rohmah, M.Pd.',
        role: 'Kepala Sekolah',
        password: '123',
        avatarUrl: 'https://picsum.photos/seed/kepsek-nyomplong/150/150',
        createdAt: '2026-08-01',
        jabatan: 'Kepala Sekolah',
        npsn: '20202020',
        namaSekolah: 'SD NEGERI 2 NYOMPLONG',
        kabupaten: 'Kota Sukabumi',
        kecamatan: 'Warudoyong',
        desa: 'Nyomplong',
        alamat: 'Jl. Nyomplong No. 45',
        provinsi: 'Jawa Barat',
      },
      {
        username: 'operator.nyomplong',
        namaLengkap: 'Hendra Gunawan, S.Pd.',
        role: 'Operator PIP',
        password: '123',
        avatarUrl: 'https://picsum.photos/seed/hendra-nyomplong/150/150',
        createdAt: '2026-08-01',
        jabatan: 'Operator PIP / Dapodik',
        npsn: '20202020',
        namaSekolah: 'SD NEGERI 2 NYOMPLONG',
        kabupaten: 'Kota Sukabumi',
        kecamatan: 'Warudoyong',
        desa: 'Nyomplong',
        alamat: 'Jl. Nyomplong No. 45',
        provinsi: 'Jawa Barat',
      },
      {
        username: 'guru.nyomplong',
        namaLengkap: 'Nurul Hidayah, S.Pd.',
        role: 'Guru',
        password: '123',
        avatarUrl: 'https://picsum.photos/seed/nurul-nyomplong/150/150',
        createdAt: '2026-08-01',
        jabatan: 'Guru Kelas / Wali Kelas 5',
        npsn: '20202020',
        namaSekolah: 'SD NEGERI 2 NYOMPLONG',
        kabupaten: 'Kota Sukabumi',
        kecamatan: 'Warudoyong',
        desa: 'Nyomplong',
        alamat: 'Jl. Nyomplong No. 45',
        provinsi: 'Jawa Barat',
      },
    ],
    siswa: [
      {
        id: 'sis-nyomp-01',
        nama: 'M. Rizky Pratama',
        nis: '202101',
        nisn: '0123456781',
        tempatLahir: 'Sukabumi',
        tanggalLahir: '12 Mei 2014',
        jenisKelamin: 'L',
        kelas: '5A',
        namaOrangTua: 'Ahmad Sudrajat',
        pekerjaanOrangTua: 'Wiraswasta',
        alamat: 'Jl. Nyomplong No. 12, Warudoyong',
        virtualAccPIP: '5241098712',
        nominalPIP: 'Rp 450.000',
      },
      {
        id: 'sis-nyomp-02',
        nama: 'Aisyah Putri Azzahra',
        nis: '202102',
        nisn: '0123456782',
        tempatLahir: 'Sukabumi',
        tanggalLahir: '24 Agustus 2013',
        jenisKelamin: 'P',
        kelas: '6B',
        namaOrangTua: 'Bambang Supriyadi',
        pekerjaanOrangTua: 'PNS',
        alamat: 'Jl. Pasundan No. 33, Warudoyong',
        virtualAccPIP: '5241098713',
        nominalPIP: 'Rp 450.000',
      },
      {
        id: 'sis-nyomp-03',
        nama: 'Fajar Nugraha',
        nis: '202103',
        nisn: '0123456783',
        tempatLahir: 'Sukabumi',
        tanggalLahir: '10 Januari 2015',
        jenisKelamin: 'L',
        kelas: '4A',
        namaOrangTua: 'Dadan Ramdani',
        pekerjaanOrangTua: 'Karyawan Swasta',
        alamat: 'Jl. Pabuaran No. 8, Warudoyong',
      },
    ],
    guru: [
      {
        id: 'gr-nyomp-01',
        nama: 'Hj. Siti Rohmah, M.Pd.',
        nip: '197405121998032004',
        pangkatGolongan: 'Pembina Tk. I, IV/b',
        jabatan: 'Kepala Sekolah',
        mapelUtama: 'Manajerial & Supervisi',
        pendidikanTerakhir: 'S2 Manajemen Pendidikan',
        statusPegawai: 'PNS',
      },
      {
        id: 'gr-nyomp-02',
        nama: 'Nurul Hidayah, S.Pd.',
        nip: '198207152006042011',
        pangkatGolongan: 'Penata Tk. I, III/d',
        jabatan: 'Guru Kelas / Wali Kelas 5',
        mapelUtama: 'Tematik Kelas 5',
        pendidikanTerakhir: 'S1 PGSD',
        statusPegawai: 'PNS',
      },
      {
        id: 'gr-nyomp-03',
        nama: 'Hendra Gunawan, S.Pd.',
        nip: '198803102014021003',
        pangkatGolongan: 'Penata Muda, III/a',
        jabatan: 'Guru PJOK & Operator',
        mapelUtama: 'Pendidikan Jasmani',
        pendidikanTerakhir: 'S1 Penjaskesrek',
        statusPegawai: 'PNS',
      },
    ],
    archives: [
      {
        id: 'arc-nyomp-01',
        category: 'mutasi',
        categoryTitle: 'Surat Keterangan Mutasi Siswa',
        nomorSurat: '421.2/015/SDN2-NYP/VIII/2026',
        penerimaAtauSubjek: 'M. Rizky Pratama',
        tanggalCetak: '10 Agustus 2026',
        dibuatOleh: 'Riki Mulyadi',
        payload: {
          namaSiswa: 'M. Rizky Pratama',
          alasanPindah: 'Mengikuti Perpindahan Tugas Orang Tua',
        },
      },
    ],
  },
  {
    npsn: '20206123',
    namaSekolah: 'SD NEGERI MARGAASIH',
    tingkat: 'SD',
    wilayah: 'Kab. Bandung, Jawa Barat',
    profile: {
      pemerintah: 'PEMERINTAH KABUPATEN BANDUNG',
      dinas: 'DINAS PENDIDIKAN',
      cabangDinas: '',
      namaSekolah: 'SD NEGERI MARGAASIH',
      npsn: '20206123',
      akreditasi: 'Akreditasi A (Amat Baik)',
      alamat: 'Jl. Margaasih Raya No. 12, RT.01/RW.05',
      kelurahan: 'Margaasih',
      kecamatan: 'Margaasih',
      kota: 'Kab. Bandung',
      provinsi: 'Jawa Barat',
      kodePos: '40215',
      telepon: '(022) 5401234',
      email: 'sdnmargaasih@bandungkab.go.id',
      website: 'www.sdnmargaasih.sch.id',
      namaKepsek: 'Drs. H. Ahmad Fauzi, M.Pd.',
      nipKepsek: '196803151992031005',
      pangkatKepsek: 'Pembina Utama Muda, IV/c',
      jabatanKepsek: 'Kepala Sekolah',
      showStempel: true,
      showTTD: true,
      showQRCode: false,
      operatorAvatarUrl: 'https://picsum.photos/seed/riki-mulyadi/150/150',
      operatorBadge: 'Operator Sekolah',
      operatorName: 'Riki Mulyadi',
      operatorSubtitle: 'Admin Tata Usaha',
      operatorChecklistTitle: 'ADMINISTRASI SEKOLAH',
      operatorChecklistItems: ['Data Siswa', 'Surat & Arsip Digital'],
      logoLeftUrl: 'https://illustrations.popsy.co/indigo/academic-cap.svg',
      logoRightUrl: 'https://illustrations.popsy.co/indigo/academic-cap.svg',
    },
    accounts: [
      {
        username: 'admin.tu',
        namaLengkap: 'Riki Mulyadi',
        role: 'Admin TU',
        password: '123',
        avatarUrl: 'https://picsum.photos/seed/riki-mulyadi/150/150',
        createdAt: '2026-08-01',
        jabatan: 'Kepala Tata Usaha',
        npsn: '20206123',
        namaSekolah: 'SD NEGERI MARGAASIH',
        kabupaten: 'Kab. Bandung',
        kecamatan: 'Margaasih',
        desa: 'Margaasih',
        alamat: 'Jl. Margaasih Raya No. 12',
        provinsi: 'Jawa Barat',
      },
      {
        username: 'kepsek',
        namaLengkap: 'Drs. H. Ahmad Fauzi, M.Pd.',
        role: 'Kepala Sekolah',
        password: '123',
        avatarUrl: 'https://picsum.photos/seed/kepsek-avatar/150/150',
        createdAt: '2026-08-01',
        jabatan: 'Kepala Sekolah',
        npsn: '20206123',
        namaSekolah: 'SD NEGERI MARGAASIH',
        kabupaten: 'Kab. Bandung',
        kecamatan: 'Margaasih',
        desa: 'Margaasih',
        alamat: 'Jl. Margaasih Raya No. 12',
        provinsi: 'Jawa Barat',
      },
      {
        username: 'operator.pip',
        namaLengkap: 'Budi Santoso, S.Pd.',
        role: 'Operator PIP',
        password: '123',
        avatarUrl: 'https://picsum.photos/seed/pip-avatar/150/150',
        createdAt: '2026-08-01',
        jabatan: 'Operator PIP / Dapodik',
        npsn: '20206123',
        namaSekolah: 'SD NEGERI MARGAASIH',
        kabupaten: 'Kab. Bandung',
        kecamatan: 'Margaasih',
        desa: 'Margaasih',
        alamat: 'Jl. Margaasih Raya No. 12',
        provinsi: 'Jawa Barat',
      },
      {
        username: 'guru',
        namaLengkap: 'Muhammad Irfan, S.Pd.',
        role: 'Guru',
        password: '123',
        avatarUrl: 'https://picsum.photos/seed/guru-avatar/150/150',
        createdAt: '2026-08-01',
        jabatan: 'Guru Kelas / Wali Kelas',
        npsn: '20206123',
        namaSekolah: 'SD NEGERI MARGAASIH',
        kabupaten: 'Kab. Bandung',
        kecamatan: 'Margaasih',
        desa: 'Margaasih',
        alamat: 'Jl. Margaasih Raya No. 12',
        provinsi: 'Jawa Barat',
      },
    ],
    siswa: [
      {
        id: 'sis-mrg-01',
        nama: 'Dimas Arya Setiawan',
        nis: '192001',
        nisn: '0098765431',
        tempatLahir: 'Bandung',
        tanggalLahir: '14 Juli 2013',
        jenisKelamin: 'L',
        kelas: '6A',
        namaOrangTua: 'Iwan Setiawan',
        pekerjaanOrangTua: 'Wiraswasta',
        alamat: 'Komp. Margaasih Permai Blok B2 No. 5',
        virtualAccPIP: '1092837465',
        nominalPIP: 'Rp 450.000',
      },
      {
        id: 'sis-mrg-02',
        nama: 'Nabila Syifa Azzahra',
        nis: '192002',
        nisn: '0098765432',
        tempatLahir: 'Bandung',
        tanggalLahir: '03 Maret 2014',
        jenisKelamin: 'P',
        kelas: '5B',
        namaOrangTua: 'Yudi Pratama',
        pekerjaanOrangTua: 'PNS',
        alamat: 'Jl. Sadang No. 19, Margaasih',
        virtualAccPIP: '1092837466',
        nominalPIP: 'Rp 450.000',
      },
    ],
    guru: [
      {
        id: 'gr-mrg-01',
        nama: 'Drs. H. Ahmad Fauzi, M.Pd.',
        nip: '196803151992031005',
        pangkatGolongan: 'Pembina Utama Muda, IV/c',
        jabatan: 'Kepala Sekolah',
        mapelUtama: 'Manajerial & Supervisi',
        pendidikanTerakhir: 'S2 Manajemen Pendidikan',
        statusPegawai: 'PNS',
      },
      {
        id: 'gr-mrg-02',
        nama: 'Budi Santoso, S.Pd.',
        nip: '198506122009021004',
        pangkatGolongan: 'Penata, III/c',
        jabatan: 'Guru Kelas 6 & Operator PIP',
        mapelUtama: 'Tematik Kelas 6',
        pendidikanTerakhir: 'S1 PGSD',
        statusPegawai: 'PNS',
      },
    ],
    archives: [
      {
        id: 'arc-mrg-01',
        category: 'keterangan_pip',
        categoryTitle: 'Surat Keterangan Bantuan PIP',
        nomorSurat: '421.2/024/SDN-MRG/VII/2026',
        penerimaAtauSubjek: 'Dimas Arya Setiawan',
        tanggalCetak: '28 Juli 2026',
        dibuatOleh: 'Budi Santoso, S.Pd.',
        payload: {
          namaSiswa: 'Dimas Arya Setiawan',
          nominalBantuan: 'Rp 450.000',
        },
      },
    ],
  },
  {
    npsn: '20203030',
    namaSekolah: 'SD NEGERI 1 SUKARAJA',
    tingkat: 'SD',
    wilayah: 'Kab. Sukabumi, Jawa Barat',
    profile: {
      pemerintah: 'PEMERINTAH KABUPATEN SUKABUMI',
      dinas: 'DINAS PENDIDIKAN, KEBUDAYAAN, KEPEMUDAAN DAN OLAHRAGA',
      cabangDinas: '',
      namaSekolah: 'SD NEGERI 1 SUKARAJA',
      npsn: '20203030',
      akreditasi: 'Akreditasi A (Unggul)',
      alamat: 'Jl. Raya Sukaraja No. 88',
      kelurahan: 'Sukaraja',
      kecamatan: 'Sukaraja',
      kota: 'Kab. Sukabumi',
      provinsi: 'Jawa Barat',
      kodePos: '43192',
      telepon: '(0266) 241555',
      email: 'sdn1sukaraja@sukabumikab.go.id',
      website: 'www.sdn1sukaraja.sch.id',
      namaKepsek: 'H. Endang Suhendar, S.Pd., M.M.Pd.',
      nipKepsek: '197108201994021001',
      pangkatKepsek: 'Pembina Tk. I, IV/b',
      jabatanKepsek: 'Kepala Sekolah',
      showStempel: true,
      showTTD: true,
      showQRCode: false,
      operatorAvatarUrl: 'https://picsum.photos/seed/deni-sukaraja/150/150',
      operatorBadge: 'Operator Sekolah',
      operatorName: 'Deni Setiawan',
      operatorSubtitle: 'Admin Tata Usaha',
      operatorChecklistTitle: 'ADMINISTRASI SEKOLAH',
      operatorChecklistItems: ['Data Siswa', 'Surat & Arsip Digital'],
      logoLeftUrl: 'https://illustrations.popsy.co/indigo/academic-cap.svg',
      logoRightUrl: 'https://illustrations.popsy.co/indigo/academic-cap.svg',
    },
    accounts: [
      {
        username: 'admin.sukaraja',
        namaLengkap: 'Deni Setiawan',
        role: 'Admin TU',
        password: '123',
        avatarUrl: 'https://picsum.photos/seed/deni-sukaraja/150/150',
        createdAt: '2026-08-01',
        jabatan: 'Kepala Tata Usaha',
        npsn: '20203030',
        namaSekolah: 'SD NEGERI 1 SUKARAJA',
        kabupaten: 'Kab. Sukabumi',
        kecamatan: 'Sukaraja',
        desa: 'Sukaraja',
        alamat: 'Jl. Raya Sukaraja No. 88',
        provinsi: 'Jawa Barat',
      },
      {
        username: 'kepsek.sukaraja',
        namaLengkap: 'H. Endang Suhendar, S.Pd., M.M.Pd.',
        role: 'Kepala Sekolah',
        password: '123',
        avatarUrl: 'https://picsum.photos/seed/kepsek-sukaraja/150/150',
        createdAt: '2026-08-01',
        jabatan: 'Kepala Sekolah',
        npsn: '20203030',
        namaSekolah: 'SD NEGERI 1 SUKARAJA',
        kabupaten: 'Kab. Sukabumi',
        kecamatan: 'Sukaraja',
        desa: 'Sukaraja',
        alamat: 'Jl. Raya Sukaraja No. 88',
        provinsi: 'Jawa Barat',
      },
      {
        username: 'operator.sukaraja',
        namaLengkap: 'Fitri Rahmawati, S.Kom.',
        role: 'Operator PIP',
        password: '123',
        avatarUrl: 'https://picsum.photos/seed/fitri-sukaraja/150/150',
        createdAt: '2026-08-01',
        jabatan: 'Operator PIP / Dapodik',
        npsn: '20203030',
        namaSekolah: 'SD NEGERI 1 SUKARAJA',
        kabupaten: 'Kab. Sukabumi',
        kecamatan: 'Sukaraja',
        desa: 'Sukaraja',
        alamat: 'Jl. Raya Sukaraja No. 88',
        provinsi: 'Jawa Barat',
      },
    ],
    siswa: [
      {
        id: 'sis-skr-01',
        nama: 'Bagas Kurniawan',
        nis: '212201',
        nisn: '0112233441',
        tempatLahir: 'Sukabumi',
        tanggalLahir: '19 September 2014',
        jenisKelamin: 'L',
        kelas: '5',
        namaOrangTua: 'Kurnia Ramdan',
        pekerjaanOrangTua: 'Petani / Wiraswasta',
        alamat: 'Kp. Pasirhalang RT.03/RW.01, Sukaraja',
        virtualAccPIP: '7788990011',
        nominalPIP: 'Rp 450.000',
      },
    ],
    guru: [
      {
        id: 'gr-skr-01',
        nama: 'H. Endang Suhendar, S.Pd., M.M.Pd.',
        nip: '197108201994021001',
        pangkatGolongan: 'Pembina Tk. I, IV/b',
        jabatan: 'Kepala Sekolah',
        mapelUtama: 'Manajerial Sekolah',
        pendidikanTerakhir: 'S2 Magister Manajemen Pendidikan',
        statusPegawai: 'PNS',
      },
    ],
    archives: [],
  },
  {
    npsn: '20204040',
    namaSekolah: 'SD NEGERI CIKOLE 1',
    tingkat: 'SD',
    wilayah: 'Kota Sukabumi, Jawa Barat',
    profile: {
      pemerintah: 'PEMERINTAH KOTA SUKABUMI',
      dinas: 'DINAS PENDIDIKAN DAN KEBUDAYAAN',
      cabangDinas: '',
      namaSekolah: 'SD NEGERI CIKOLE 1',
      npsn: '20204040',
      akreditasi: 'Akreditasi A (Unggul)',
      alamat: 'Jl. RE. Martadinata No. 25',
      kelurahan: 'Cikole',
      kecamatan: 'Cikole',
      kota: 'Kota Sukabumi',
      provinsi: 'Jawa Barat',
      kodePos: '43113',
      telepon: '(0266) 221199',
      email: 'sdncikole1@sukabumikota.sch.id',
      website: 'www.sdncikole1.sch.id',
      namaKepsek: 'Dra. Hj. Nina Herlina, M.Si.',
      nipKepsek: '197211101997022002',
      pangkatKepsek: 'Pembina Utama Muda, IV/c',
      jabatanKepsek: 'Kepala Sekolah',
      showStempel: true,
      showTTD: true,
      showQRCode: false,
      operatorAvatarUrl: 'https://picsum.photos/seed/wawan-cikole/150/150',
      operatorBadge: 'Operator Sekolah',
      operatorName: 'Wawan Gunawan',
      operatorSubtitle: 'Admin Tata Usaha',
      operatorChecklistTitle: 'ADMINISTRASI SEKOLAH',
      operatorChecklistItems: ['Data Siswa', 'Surat & Arsip Digital'],
      logoLeftUrl: 'https://illustrations.popsy.co/indigo/academic-cap.svg',
      logoRightUrl: 'https://illustrations.popsy.co/indigo/academic-cap.svg',
    },
    accounts: [
      {
        username: 'admin.cikole',
        namaLengkap: 'Wawan Gunawan',
        role: 'Admin TU',
        password: '123',
        avatarUrl: 'https://picsum.photos/seed/wawan-cikole/150/150',
        createdAt: '2026-08-01',
        jabatan: 'Kepala Tata Usaha',
        npsn: '20204040',
        namaSekolah: 'SD NEGERI CIKOLE 1',
        kabupaten: 'Kota Sukabumi',
        kecamatan: 'Cikole',
        desa: 'Cikole',
        alamat: 'Jl. RE. Martadinata No. 25',
        provinsi: 'Jawa Barat',
      },
      {
        username: 'kepsek.cikole',
        namaLengkap: 'Dra. Hj. Nina Herlina, M.Si.',
        role: 'Kepala Sekolah',
        password: '123',
        avatarUrl: 'https://picsum.photos/seed/kepsek-cikole/150/150',
        createdAt: '2026-08-01',
        jabatan: 'Kepala Sekolah',
        npsn: '20204040',
        namaSekolah: 'SD NEGERI CIKOLE 1',
        kabupaten: 'Kota Sukabumi',
        kecamatan: 'Cikole',
        desa: 'Cikole',
        alamat: 'Jl. RE. Martadinata No. 25',
        provinsi: 'Jawa Barat',
      },
    ],
    siswa: [
      {
        id: 'sis-ckl-01',
        nama: 'Revan Aditya',
        nis: '222301',
        nisn: '0134567891',
        tempatLahir: 'Sukabumi',
        tanggalLahir: '05 Mei 2014',
        jenisKelamin: 'L',
        kelas: '6A',
        namaOrangTua: 'Aditya Pratama',
        pekerjaanOrangTua: 'Wiraswasta',
        alamat: 'Jl. Cikole Dalam No. 17, Cikole',
      },
    ],
    guru: [
      {
        id: 'gr-ckl-01',
        nama: 'Dra. Hj. Nina Herlina, M.Si.',
        nip: '197211101997022002',
        pangkatGolongan: 'Pembina Utama Muda, IV/c',
        jabatan: 'Kepala Sekolah',
        mapelUtama: 'Manajerial Sekolah',
        pendidikanTerakhir: 'S2 Ilmu Administrasi',
        statusPegawai: 'PNS',
      },
    ],
    archives: [],
  },
  {
    npsn: '20205050',
    namaSekolah: 'SMP NEGERI 1 SUKABUMI',
    tingkat: 'SMP',
    wilayah: 'Kota Sukabumi, Jawa Barat',
    profile: {
      pemerintah: 'PEMERINTAH KOTA SUKABUMI',
      dinas: 'DINAS PENDIDIKAN DAN KEBUDAYAAN',
      cabangDinas: '',
      namaSekolah: 'SMP NEGERI 1 SUKABUMI',
      npsn: '20205050',
      akreditasi: 'Akreditasi A (Unggul)',
      alamat: 'Jl. Veteran No. 10',
      kelurahan: 'Selabatu',
      kecamatan: 'Cikole',
      kota: 'Kota Sukabumi',
      provinsi: 'Jawa Barat',
      kodePos: '43111',
      telepon: '(0266) 221888',
      email: 'smpn1kotasukabumi@yahoo.co.id',
      website: 'www.smpn1sukabumi.sch.id',
      namaKepsek: 'Dr. H. Mulyadi, M.Pd.',
      nipKepsek: '196904141995121002',
      pangkatKepsek: 'Pembina Utama Madya, IV/d',
      jabatanKepsek: 'Kepala Sekolah',
      showStempel: true,
      showTTD: true,
      showQRCode: false,
      operatorAvatarUrl: 'https://picsum.photos/seed/asep-smpn1/150/150',
      operatorBadge: 'Operator Sekolah',
      operatorName: 'Asep Saepuloh, S.AP.',
      operatorSubtitle: 'Admin Tata Usaha',
      operatorChecklistTitle: 'ADMINISTRASI SEKOLAH',
      operatorChecklistItems: ['Data Siswa', 'Surat & Arsip Digital'],
      logoLeftUrl: 'https://illustrations.popsy.co/indigo/academic-cap.svg',
      logoRightUrl: 'https://illustrations.popsy.co/indigo/academic-cap.svg',
    },
    accounts: [
      {
        username: 'admin.smpn1',
        namaLengkap: 'Asep Saepuloh, S.AP.',
        role: 'Admin TU',
        password: '123',
        avatarUrl: 'https://picsum.photos/seed/asep-smpn1/150/150',
        createdAt: '2026-08-01',
        jabatan: 'Kepala Tata Usaha',
        npsn: '20205050',
        namaSekolah: 'SMP NEGERI 1 SUKABUMI',
        kabupaten: 'Kota Sukabumi',
        kecamatan: 'Cikole',
        desa: 'Selabatu',
        alamat: 'Jl. Veteran No. 10',
        provinsi: 'Jawa Barat',
      },
      {
        username: 'kepsek.smpn1',
        namaLengkap: 'Dr. H. Mulyadi, M.Pd.',
        role: 'Kepala Sekolah',
        password: '123',
        avatarUrl: 'https://picsum.photos/seed/kepsek-smpn1/150/150',
        createdAt: '2026-08-01',
        jabatan: 'Kepala Sekolah',
        npsn: '20205050',
        namaSekolah: 'SMP NEGERI 1 SUKABUMI',
        kabupaten: 'Kota Sukabumi',
        kecamatan: 'Cikole',
        desa: 'Selabatu',
        alamat: 'Jl. Veteran No. 10',
        provinsi: 'Jawa Barat',
      },
    ],
    siswa: [
      {
        id: 'sis-smp-01',
        nama: 'Arya Bima Perkasa',
        nis: '2122001',
        nisn: '0087654321',
        tempatLahir: 'Sukabumi',
        tanggalLahir: '18 Februari 2011',
        jenisKelamin: 'L',
        kelas: '7A',
        namaOrangTua: 'Bambang Perkasa',
        pekerjaanOrangTua: 'PNS',
        alamat: 'Jl. Suryakencana No. 40, Cikole',
      },
    ],
    guru: [
      {
        id: 'gr-smp-01',
        nama: 'Dr. H. Mulyadi, M.Pd.',
        nip: '196904141995121002',
        pangkatGolongan: 'Pembina Utama Madya, IV/d',
        jabatan: 'Kepala Sekolah',
        mapelUtama: 'Manajerial Sekolah',
        pendidikanTerakhir: 'S3 Manajemen Pendidikan',
        statusPegawai: 'PNS',
      },
    ],
    archives: [],
  },
];
